<a href="https://colab.research.google.com/gist/marcos626/3a2c57cff11991943017137963ea17b8/redes-neuronales-2024-guia-2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Familiarizandose con **Numpy**

Referencias:
* https://www.datacamp.com/cheat-sheet/numpy-cheat-sheet-data-analysis-in-python
* https://towardsdatascience.com/a-cheat-sheet-on-generating-random-numbers-in-numpy-5fe95ec2286

## **Ejercicio 1)** Importando librerías

Importe las librerías `numpy` para operar con arrays, `scipy` para operar con algebra lineal y `matplotlib.pyplot` para graficar.

In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt

## **Ejercicio 2)** Creando arrays

**1)** Cree un array de enteros `a` a partir de la lista `[1,2,3]`.

**2)** Cree un array bidimensional de flotantes `b` a partir de la lista de listas `[[1.5,2,3],[4,5,6]]`.

**3)** Cree un array tridimensional de flotantes `c` a partir de la lista de listas `[[[1.5,2,3],[4,5,6]],[[3,2,1],[4,5,6]]]`.

In [4]:
# 2.1)
a = np.array([1,2,3])
# 2.2)
b = np.array([[1.5,2,3],[4,5,6]])
# 2.3)
c = np.array([[[1.5,2,3],[4,5,6]],[[3,2,1],[4,5,6]]])

In [6]:
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

## **Ejercicio 3)** Inicializando arrays

**1)** Utilice `np.zeros` para crear un array bidimensional de flotantes incializados a `0.0`, y de dimensiones de tamaños `(3,4)`.

**2)** Utilice `np.ones` para crear un array tridimensional de enteros inicializados a `1`, y de dimensiones `(2,3,4)`.

**3)** Utilice `np.arange` para crear un array `d` de valores enteros equiespaciados de a `5` entre `10` y `25`.

**4)** Utilice `np.linspace` para crear un array de `9` valores flotantes equiespaciados entre `0.0` y `9.0`.

**5)** Utilice `np.full` para crear un array bidimensional llamado `e` de entradas iguales a `7`, y de dimesiones `(2,2)`.

**6)** Utilice `np.eye` para crear una matriz identidad llamada `f` de dimensiones 2x2.

**7)** Utilice `np.random.random` para crear un array bidimensional de dimensiones 2x2 inicializado con valores aleatorios uniformemente sorteados del intervalo $[0,1]$.

**8)** Utilice `np.empty` para crear un array bidimensional sin inicializar y de dimensiones `(3,2)`.


In [9]:
# 3.1)
np.zeros((3,4)) #Create an array of zeros
# 3.2)
np.ones((2,3,4), dtype=np.int16) #Create an array of ones
# 3.3)
np.arange(10,25,5) #Create an array of evenly spaced values (step value)
# 3.4)
np.linspace(0,9,9) #Create an array of evenly spaced values (number of samples)
# 3.5)
e = np.full((2,2),7) #Create a constant array
# 3.6)
f = np.eye(2) #Create a 2X2 identity matrix
# 3.7)
np.random.random((2,2)) #Create an array with random values
# 3.8)
np.empty((3,2)) #Create an empty array

array([[1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309]])

## **Ejercicio 4)** Inspeccionando arrays

Considere los arrays de los ejercicios 2) y 3).

**1)** Utilizando `.shape`, determine cuales son las dimensiones del array `a`.

**2)** Utilizando la función `len()`, determine el *largo* del array `a`.

**3)** Utilizando `.ndim`, determine el número de dimensiones del array `b`.

**4)** Utilizando `.size`, determine el número de entradas que tienen `e`.

**5)** Utilizando `.dtype`, determine el tipo de los datos contenidos por el array `b`.

**6)** Utilizando `.dtype.name`, determine el nombre del tipo de los datos contenidos por el array `b`.

**7)** Utilizando `.astype`, convierta el array `b` a un array de tipo `int`.



In [80]:
# 4.1)
a.shape #Array dimensions
# 4.2)
len(a) #Length of array
# 4.3)
b.ndim #Number of array dimensions
# 4.4)
#e.size #Number of array elements
# 4.5)
b.dtype #Data type of array elements
# 4.6)
b.dtype.name #Name of data type
# 4.7)
b.astype(int) #Convert an array to a different type

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
print(c.ndim)
c.shape

3


(2, 2, 3)

## **Ejercicio 5)** Tipos de datos

**1)** Cree un array que contenga elementos de tipo `np.int64`.

**2)** Cree un array que contenga elementos de tipo `np.float32`.

**3)** Cree un array que contenga elementos de tipo `np.complex`.

**4)** Cree un array que contenga elementos de tipo `np.bool`.

**5)** Cree un array que contenga elementos de tipo `np.object`.

**6)** Cree un array que contenga elementos de tipo `np.string_`.

**7)** Cree un array que contenga elementos de tipo `np.unicode_`.

In [17]:
# 5.1)
np.array([1,2,3], dtype=np.int64)
# 5.2)
np.array([1,2,3], dtype=np.float32)
# 5.3)
np.array([1+3.j,2,3], dtype=complex)
# 5.4)
np.array([1,2,3], dtype=bool)
# 5.5)
np.array([1,"hola",[3,4]], dtype=object)
# 5.6)
np.array(["hola","mundo","argentina"], dtype=np.string_)
# 5.7)
np.array(["hola","mundo",u'\U0001F600',u'\u03bcm'], dtype=np.unicode_)

array(['hola', 'mundo', '😀', 'μm'], dtype='<U5')

In [19]:
np.array(["hola","mundo",u'\u03bcm'], dtype=np.unicode_)

array(['hola', 'mundo', 'μm'], dtype='<U5')

## **Ejercicio 6)** Operando sobre arrays

Considere los arrays de los ejercicios 2) y 3).

**1)** Calcule la resta `a-b` de los arrays `a` y `b` y almacene el resultado en un array `g`.

**2)** Notar que `a` y `b` poseen diferentes dimensiones (i.e., `a.shape` es distinto de `b.shape`) y, sin embargo, en el inciso anterior numpy computa la suma `a+b`. Explique lo que ocurre.

**3)** Compare el anterior resultado con el uso de `np.substract`.

**4)** Calcule la suma `a-b` de los arrays `a` y `b`.

**5)** Compare el anterior resultado con el uso de `np.add`.

**6)** Calcule la división punto a punto  `a/b` de `a` y `b`.

**7)** Compare el anterior resultado con el uso de `np.divide`.

**8)** Calcule la multiplicación punto a punto  `a*b` de `a` y `b`.

**9)** Compare el anterior resultado con el uso de `np.multiply`.

**10)** Calcule la exponencial punto a punto  `np.exp(b)` de `b`.

**11)** Calcule la raíz cuadrada punto a punto  `np.sqrt(b)` de `b`.

**12)** Calcule el seno punto a punto  `np.sin(a)` de `a`.

**13)** Calcule el coseno punto a punto  `np.sin(b)` de `b`.

**14)** Calcule el logaritmo natural punto a punto  `np.log(a)` de `a`.

**15)** Calcule el producto punto `e.dot(f)` entre `e` y `f`.

**16)** Compare el anterior resultado con el uso de `np.dot`.

**17)** Explique las diferentes opciones que puede adoptar el producto punto de numpy según el número de dimensiones que tengan sus factores.

**Ayuda:** use https://numpy.org/doc/stable/reference/generated/numpy.dot.html

In [22]:
# 6.1)
g = a-b #Substraction

In [24]:
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [26]:
# 6.3)
np.subtract(a,b) #Substraction
# 6.4)
b+a #Addition
# 6.5)
np.add(b,a) #Addition
# 6.6)
a/b #Division
# 6.7)
np.divide(a,b) #Division
# 6.8)
a*b #Multiplication
# 6.9)
np.multiply(a,b) #Multiplication
# 6.10)
np.exp(b) #Exponentiation
# 6.11)
np.sqrt(b) #Square root
# 6.12)
np.sin(a) #Sine
# 6.13)
np.cos(b) #Cosine
# 6.14)
np.log(a) #Natural logarithm
# 6.15)
e.dot(f) #Dot product
# 6.16)
np.dot(e,f) #Dot product

array([[7., 7.],
       [7., 7.]])

In [28]:
e.dot(f)

array([[7., 7.],
       [7., 7.]])

## **Ejercicio 7)** Comparando arrays

**1)** Use `==` para realizar una compación punto a punto de los arrays `a` y `b`.

**2)** Use `<` para realizar una comparación punto a punto del array `b` con el escalar `2`.

**3)** Use `np.array_equal(a,b)` para determinar si `a` y `b` son iguales como arrays.

In [31]:
# 7.1)
a == b #Elementwise comparison
# 7.2)
b < 2 #Elementwise comparison
# 7.3)
np.array_equal(a,b) #Arraywise comparison

False

In [33]:
np.array_equal(a,b)

False

## **Ejercicio 8)** *Copiando* arrays

**1)** Use `.view()` para crear una vista llamada `h` del array `a`.

**2)** Use `.copy()` para crear una copia del array `a`.

In [36]:
# 8.1)
h = a.view() #Create a view of the array with the same data
# 8.2)
np.copy(a) #Create a copy of the array
# 8.2.2)
#h = a.copy() #Create a deep copy of the array

array([1, 2, 3])

In [38]:
a = np.array([1,2,3])

In [40]:
a

array([1, 2, 3])

In [42]:
h = a.view()

In [44]:
h

array([1, 2, 3])

In [46]:
h[1] = 100

In [48]:
h

array([  1, 100,   3])

In [50]:
a

array([  1, 100,   3])

## **Ejercicio 9)** Ordenado

**1)** Use `.sort()` para ordenar los elementos de `a`.

**2)** Ordene los elementos de `c` a lo largo del eje `0`. Explique.

In [53]:
# 9.1)
a.sort() #Sort an array
# 9.2)
c.sort(axis=0) #Sort the elements of an array's axis

## **Ejercicio 10)** Indexado y *slicing* (rebanado) de arrays

**1)** Seleccione el segundo elemento de `a`.

**2)** Seleccione el elemento en la fila 1 y columna 2 de `b`.

Si `n` y `m` son enteros, luego `[n:m]` indica el rango de índices que van desde `n` hasta `m-1`.

**3)** Seleccione el rango `[0:2]` de elementos de `a`.

**4)** Seleccione los elementos de `b` en el rango `[0:2]` de filas y la columna `1`.

**5)** Seleccione todos los elementos de `b` que esten en el rango de filas `[0:1]` y el rango completo de columnas.

**6)** Uso de *elipsis*. Seleccione los elementos de `c` indexados por `[1,...]`. Es esto lo mismo que lo indexado por `[1,:,:]`?

Si `n`, `m` y `s` son enteros, luego `[n:m:s]` indica el rango de índices que van desde `n` hasta `m-1` saltando de a `s` elementos.

**7)** Utilice lo mencionado anteriormente para acceder a los elementos de `a` de forma invertida.

**8)** Seleccione los elementos de `a` que sean menores que dos.

**9)** Seleccione los elementos de `b` indicados por la lista de índices `[(1,0),(0,1),(1,2),(0,0)]` utilizando, correspondientemente, una lista de indices fila y una lista de índices columna.

**10)** Utilizando una lista de indices fila, seleccione las filas `1,0,1,0` de `b`, y luego, para cada selección anterior, utilice una lista de índices columna para seleccionar las columnas `0,1,2,0`.

In [56]:
# 10.1)
a[1] #Select the element
# 10.2)
b[1,2] #Select the element
# 10.3)
a[0:2] #Select items at index 0 and 1. Esto es una rebanada o slice
# 10.4)
b[0:2,1] #Select items at rows 0 and 1 in column 1
# 10.5)
b[:,1] #Select all items at row 0
# 10.6)
c[1,...] #Same as [1,:,:]
# 10.7)
a[::-1] #Reversed array a
# 10.8)
a[a<2] #Select elements from a less than 2
# 10.9)
b[[1,0,1,0],[0,1,2,0]] #Select elements (1,0),(0,1),(1,2) and (0,0)
# 10.10)
b[[1,0,1,0]][:,[0,1,2,0]] #Select a subset of the matrix’s rows and columns


array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

## **Ejercicio 11)** transposición

**1)** Use `np.transpose()` para calcular la traspuesta del array `b`, y asignarlo a una variable `i`.

**2)** Use `.T` para acceder a `i` de forma traspuesta. Es esta forma traspuesta igual a `b`?

In [59]:
# 11.1)
np.transpose(b) #Transpose
# 11.2)
i = np.transpose(b) #Transpose
i = i.T #Transpose

## **Ejercicio 12)** Redimensionado

**1)** Use `.ravel()` para *achatar* el array `b`.

**2)** Use `.reshape()` para redimensionar el array `g` de manera que adquiera dimensiones especificadas por la tupla `(3,-2)`.

**3)** Que indica aquí el signo negativo del segundo índice?

In [62]:
# 12.1)
b.ravel() #Flatten the array
# 12.2)
g.reshape((3,-2)) #Reshape, but don’t change data

array([[-0.5,  0. ],
       [ 0. , -3. ],
       [-3. , -3. ]])

## **Ejercicio 13)** Agregando y quitando elementos

**1)** Use `np.resize()` para crear a partir del array `h` un nuevo array de tamaño y dimensiones diferentes indicadas por `(2,6)`.

**2)** Use `np.append()` para crear un nuevo array que agrege los elementos de `g` al final de los elementos de `h`. Notar que `h` y `g` tienen diferentes dimensiones. Cómo resuelve `numpy` esta cuestión?

**3)** Use `np.insert()` para crear una copia de `a` en donde se inserta el número `5` en la posición indexada por `1`.

**4)** Use `np.delete()` para eliminar los elementos de `a` indicados por la lista de índices `[1]`.

In [65]:
# 13.1)
np.resize(h,(2,6)) #Return a new array with the specified size
# 13.2)
np.append(h,g) #Append items to an array
# 13.3)
np.insert(a,1,5) #Insert items in an array
# 13.4)
np.delete(a,[1]) #Delete items from an array

array([  1, 100])

## **Ejercicio 14)** Combinando arrays

**a)** Use `np.concatenate()` para concatenar los arrays `a` y `d`.

**b)** Use `np.vstack()` para apilar verticalmente los arrays `a` y `b`.

**c)** Use `np.row_stack()` para apilar verticalmente los arrays `e` y `f`.

**d)** Use `np.hstack()` para apilar horizontalmente los arrays `e` y `f`.

**e)** Use `np.column_stack()` para apilar horizontalmente los arrays `a` y `d`.

In [68]:
# 14.1)
np.concatenate((a,d)) #Concatenate arrays
# 14.2)
np.vstack((a,b)) #Stack arrays vertically (row-wise)
# 14.3)
np.row_stack((e,f)) #Stack arrays vertically (row-wise)
# 14.4)
np.hstack((e,f)) #Stack arrays horizontally (column-wise)
# 14.5)
np.column_stack((a,d)) #Create stacked column-wise arrays


NameError: name 'd' is not defined

## **Ejercicio 15)** *Separando* arrays

**a)** Use `np.hsplit()` para separar horizontalmente el array `a` en 3 partes.

**b)** Use `np.vsplit()` para separar verticalmente el array `c` en 2 partes.

**c)** Cree el array `z` dado por

    [[1, 2, 3, 4],
    [2, 0, 0, 2],
    [3, 1, 1, 0]]

y sepárelo en dos partes a lo largo del eje `1`.

In [ ]:
# 15.1)
np.hsplit(a,3) #Split an array into several sub-arrays horizontally (column-wise)
# 15.2)
np.vsplit(c,2) #Split an array into several sub-arrays vertically (row-wise)
# 15.3)

## **Ejercicio 16)** Generando números aleatorios

**1)** Use `np.random.random()` para generar un número aleatorio de tipo float64 a partir de la distribución uniforme en $[0,1]$.

**2)** Use `np.random.random()` para crear un array de 10 números aleatorios de tipo float64 generados a partir de la distribución uniforme en $[0,1]$.

**3)** Use `np.random.random()` para crear un array dos dimensional de dimensiones `(3,4)` conteniendo números aleatorios de tipo float64 generados a partir de la distribución uniforme en $[0,1]$.

**4)** Use `np.random.randn()` para generar un número aleatorio de tipo float64 a partir de la distribución normal centrada en $\mu=0$ y de varianza $\sigma^2=1$.

**5)** Use `np.random.randn()` para generar un número aleatorio de tipo float64 a partir de la distribución normal centrada en $\mu=5$ y de varianza $\sigma^2=9$.

**6)** Use `np.random.randn()` para generar un array de dimensiones `(3,2,3)` conteniendo números aleatorios de tipo float64 generados a partir de la distribución normal centrada en $\mu=-1$ y de varianza $\sigma^2=2$.

**7)** Use `np.random.randint()` para generar un número aleatorio de tipo int64 a partir de la distribución uniforme en $\{0,1,2,3\}$.

**8)** Use `np.random.randint()` para generar un número aleatorio de tipo int64 a partir de la distribución uniforme en $\{10,11,12,13,14,15\}$.

**9)** Use `np.random.randint()` para generar un array de dimensiones `(3,2,3)` conteniendo números aleatorios de tipo int64 generados a partir de la distribución uniforme en $\{0,1\}$.

**10)** Use `np.random.choice()` para seleccionar uniformemente al azar un elemento de la lista `["perro","gato","loro","caballo","vaca"]`.

**11)** Use `np.random.choice()` para crear un array de dimensiones `(3,3)` con selecciones generadas uniformemente al azar de los elementos de la lista `["perro","gato","loro","caballo","vaca"]`.

**12)** Use `np.random.choice()` para crear un array de dimensiones `(3,3,3)` con selecciones generadas al azar de los elementos de la lista `["perro","gato","loro","caballo","vaca"]` de acuerdo a la correspondiente lista de probabilidades `[8/16,4/16,2/16,1/16,1/16]`.

**13)** Use `np.random.permutation()` generar una permutación, seleccionada uniformemente al azar una de las `n!` permutaciones que existen de un conjunto de `n` elementos, de una la lista de números entre `0` y `n-1` para `n=10` denominada `lista_n`.

**14)** Repita lo anterior usando `np.random.shuffle()` para aleatorizar la lista `lista_n` *in situ*.

In [ ]:
# 16.1)
np.random.random() #Return random floats in the half-open interval [0.0, 1.0)
# 16.2)
np.random.random(10) #Return random floats in the half-open interval [0.0, 1.0)
# 16.3)
np.random.random((3,4)) #Return random floats in the half-open interval [0.0, 1.0)
# 16.4
np.random.randn() #Return a sample (or samples) from the “standard normal” distribution.
# 16.5
np.random.randn(5) #Return a sample (or samples) from the “standard normal” distribution.
# 16.6
np.random.randn(3,2,3) #Return a sample (or samples) from the “standard normal” distribution.
# 16.7
np.random.randint(4) #Return random integers from low (inclusive) to high (exclusive).
# 16.8
np.random.randint(10,1